### ISSUE TITLE
Distributed Tracing page won’t Load on Chrome

### ISSUE THREAD

**Issue by sampeinado** [Azure/Azure-Spring-Cloud#6]
**Currently:**
When clicking on the Distributed Tracing button in the right menu, the main content on the page never loads and a loading animation stays up indefinitely. 

**Expected:**
When clicking on the Distributed Tracing button in the right menu, loading animation stays up briefly and the page content loads quickly. 

**STEPS TO REPRODUCE:**
Using Chrome Version 77.0.3865.120 (Official Build) (64-bit), click on the Distributed Tracing button in the right menu.

**REFERENCE:**
<img width="637" alt="Screenshot 2019-10-28 at 11 23 15 AM" src="https://user-images.githubusercontent.com/35495560/67692506-9c955400-f976-11e9-9813-3f7dbe809bb5.png">

The error in regular Chrome window:
```
Version: 5.0.302.60501 (production#8a563c8b80.191022-1430) Signed
Session: 5031b064b04a482ab4b141be32f1dd45
c286befa-ee95-42c9-a9e3-d5be4347dc90:1 Extension: HubsExtension
aM7qSd17daJy.js:1 batchResponseItem: {"httpStatusCode":200,"headers":{"Pragma":"no-cache","Transfer-Encoding":"chunked","Vary":"Accept-Encoding,Accept-Encoding","x-ms-correlation-request-id":"3680e809-e346-4f40-a32f-d128909608ab","x-ms-ratelimit-remaining-subscription-reads":"11999","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","x-ms-client-request-id":"c5e278dd-67bb-454d-af22-2b46f90af000","x-rp-server-mvid":"0aa55a30-5cd5-429c-af4f-e30df7629491","x-ms-request-id":"b51b61f9-a901-4600-b9aa-1bff1af7d4d6","x-ms-routing-request-id":"CANADACENTRAL:20191028T152918Z:b3fa5b0b-ebc5-41a2-af70-62d684312791","Cache-Control":"no-cache","Date":"Mon, 28 Oct 2019 15:29:18 GMT","Server":"openresty/1.15.8.1"},"content":{"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"},"contentLength":459}
aM7qSd17daJy.js:1 content: {"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"}
aM7qSd17daJy.js:1 batchResponseItem: {"httpStatusCode":200,"headers":{"Pragma":"no-cache","Transfer-Encoding":"chunked","Vary":"Accept-Encoding,Accept-Encoding","x-ms-correlation-request-id":"56ae01a9-1fc7-4b57-992e-8564eb5f2238","x-ms-ratelimit-remaining-subscription-reads":"11998","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","x-ms-client-request-id":"c5e278dd-67bb-454d-af22-2b46f90af001","x-rp-server-mvid":"0aa55a30-5cd5-429c-af4f-e30df7629491","x-ms-request-id":"d54b1da4-98b2-479d-b089-95e38907cf02","x-ms-routing-request-id":"CANADACENTRAL:20191028T152919Z:c329fb96-d64c-4b54-9dfd-c8b2413fb8ef","Cache-Control":"no-cache","Date":"Mon, 28 Oct 2019 15:29:18 GMT","Server":"openresty/1.15.8.1"},"content":{"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"},"contentLength":459}
aM7qSd17daJy.js:1 content: {"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"}
d54PHuFc6uBX.js:9 [AppPlatformExtension]  11:29:19 AM Extension/AppPlatformExtension/PartType/Resource$TracingBladeAdapter Resource$TracingBladeAdapter: _errorData: undefined
_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.Error"]
code: undefined
data: {
  <u>: {
    content: <function>i,
    onInputsSetPromiseState: <function>i,
    role: <number>,
    internal: <Object>,
    container: <e>,
    onInputsSetPromise: <i>,
    chrome: <Object>,
    getViewModelStart: <number>
  }
}
errorLevel: 2
extension: AppPlatformExtension
handled: undefined
innerErrors: ["message: Cannot read property 'length' of undefined\r\nstack: TypeError: Cannot read property 'length' of undefined\n    at d (https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3297)\n    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3234\n    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)\n    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5156\r\n"]
message: Part's onInputsSet promise failed.(id: AppPlatformExtension-fx-010-000)
name: Error
source: undefined
stack: Error: Part's onInputsSet promise failed.(id: AppPlatformExtension-fx-010-000)
    at new r (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:18:790)
    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:72:2971
    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)
    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5443
timestamp: 1958.904999992228
type: MsPortalFx.Errors.Error

r @ d54PHuFc6uBX.js:9
d54PHuFc6uBX.js:9 [AppPlatformExtension]  11:29:19 AM Base.ProxiedObservablesV2 241 Base.ProxiedObservablesV2: Po-241: 
{"message":"Cannot read property 'properties' of undefined","callstack":"TypeError: Cannot read property 'properties' of undefined\n    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/A5nB-lyFRmeE.js:1:6029\n    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10418)\n    at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9964)\n    at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9477)\n    at Function.peek (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10673)\n    at lo (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:9106)\n    at p (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:12169)\n    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5660\n    at li (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:2981)\n    at su (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5520)\n    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17478\n    at ot (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5771)\n    at Function.tr.notifySubscribers (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17675)\n    at Function.valueHasMutated (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:3337)\n    at u.i [as content] (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:3059)\n    at https://portal.azure.com/Content/Dynamic/fcqQdQiIcD3V.js:54:1590\n    at n.<anonymous> (https://portal.azure.com/Content/Dynamic/fcqQdQiIcD3V.js:54:934)\n    at n.callback (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:23:1395)\n    at Function.notifySubscribers (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:1585)\n    at Function.tr.notifySubscribers (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17645)\n    at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10171)\n    at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9477)\n    at Function.evaluatePossiblyAsync (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9081)\n    at Function.notifySubscribers (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:1585)\n    at Function.tr.notifySubscribers (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17753)\n    at Function.valueHasMutated (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:3337)\n    at Function.remove (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:4764)\n    at f (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:126:8003)\n    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)\n    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5156","pId":"AppPlatformExtension-fx-01","data":"AppPlatformExtension-fx-010-002:{\n  <t>: {\n    menuContent: <Object>,\n    subtitle: <function>i,\n    icon: <function>i,\n    statusBar: <function>i,\n    helpContentUri: <function>i,\n    title: <function>i,\n    commandBar: <t>,\n    contentSection: <t>,\n    emptyContentSection: <t>\n  }\n}"}
r @ d54PHuFc6uBX.js:9
d54PHuFc6uBX.js:9 [AppPlatformExtension]  11:29:28 AM MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Cannot read property 'length' of undefined
stack: TypeError: Cannot read property 'length' of undefined
    at d (https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3297)
    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3234
    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)
    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5156

r @ d54PHuFc6uBX.js:9
d54PHuFc6uBX.js:9 [AppPlatformExtension]  11:29:28 AM MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Cannot read property 'properties' of undefined
stack: TypeError: Cannot read property 'properties' of undefined
    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/A5nB-lyFRmeE.js:1:6029
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10418)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9964)
    at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9477)
    at Function.peek (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10673)
    at lo (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:9106)
    at p (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:12169)
    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5660
    at li (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:2981)
    at su (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5520)
    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17478
    at ot (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5771)
    at Function.tr.notifySubscribers (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17675)
    at Function.valueHasMutated (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:3337)
    at u.i [as content] (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:3059)
    at https://portal.azure.com/Content/Dynamic/fcqQdQiIcD3V.js:54:1590
    at n.<anonymous> (https://portal.azure.com/Content/Dynamic/fcqQdQiIcD3V.js:54:934)
    at n.callback (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:23:1395)
    at Function.notifySubscribers (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:1585)
    at Function.tr.notifySubscribers (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17645)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10171)
    at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9477)
    at Function.evaluatePossiblyAsync (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9081)
    at Function.notifySubscribers (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:1585)
    at Function.tr.notifySubscribers (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:17753)
    at Function.valueHasMutated (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:3337)
    at Function.remove (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:4764)
    at f (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:126:8003)
    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)
    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5156

```

The error in Chrome “Incognito Mode” window:
```Version: 5.0.302.60501 (production#8a563c8b80.191022-1430) Signed
Session: 9a927cd2a41f4ca695d887ed27ad74c4
397a4457-3039-4dba-bec2-f6f989d558e5:1 Extension: HubsExtension
aM7qSd17daJy.js:1 batchResponseItem: {"httpStatusCode":200,"headers":{"Pragma":"no-cache","Transfer-Encoding":"chunked","Vary":"Accept-Encoding,Accept-Encoding","x-ms-correlation-request-id":"9f572b89-fbff-4cc5-8068-abaf086fbfb4","x-ms-ratelimit-remaining-subscription-reads":"11998","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","x-ms-client-request-id":"3eda290d-305c-4d55-8236-6105962d8000","x-rp-server-mvid":"0aa55a30-5cd5-429c-af4f-e30df7629491","x-ms-request-id":"3fcfd809-e3c0-4ef3-9272-5f0dac778b8c","x-ms-routing-request-id":"CANADACENTRAL:20191028T143902Z:4cf0e6f9-3d58-459a-a852-3c193cc01b10","Cache-Control":"no-cache","Date":"Mon, 28 Oct 2019 14:39:01 GMT","Server":"openresty/1.15.8.1"},"content":{"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"},"contentLength":459}
aM7qSd17daJy.js:1 content: {"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"}
aM7qSd17daJy.js:1 batchResponseItem: {"httpStatusCode":200,"headers":{"Pragma":"no-cache","Transfer-Encoding":"chunked","Vary":"Accept-Encoding,Accept-Encoding","x-ms-correlation-request-id":"5bdd8303-bcc8-4bf7-a4c8-46773ac8829b","x-ms-ratelimit-remaining-subscription-reads":"11997","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","x-ms-client-request-id":"3eda290d-305c-4d55-8236-6105962d8001","x-rp-server-mvid":"0aa55a30-5cd5-429c-af4f-e30df7629491","x-ms-request-id":"e70ea803-6175-40bf-82c9-f1fc14f83537","x-ms-routing-request-id":"CANADACENTRAL:20191028T143903Z:3ca7af46-273e-4c24-a266-9c2c5d2ea21e","Cache-Control":"no-cache","Date":"Mon, 28 Oct 2019 14:39:02 GMT","Server":"openresty/1.15.8.1"},"content":{"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"},"contentLength":459}
aM7qSd17daJy.js:1 content: {"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"}
aM7qSd17daJy.js:1 batchResponseItem: {"httpStatusCode":200,"headers":{"Pragma":"no-cache","Transfer-Encoding":"chunked","Vary":"Accept-Encoding,Accept-Encoding","x-ms-correlation-request-id":"f906f6aa-c08b-4f86-9559-d91450773a51","x-ms-ratelimit-remaining-subscription-reads":"11997","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","x-ms-client-request-id":"3eda290d-305c-4d55-8236-6105962d8006","x-rp-server-mvid":"0aa55a30-5cd5-429c-af4f-e30df7629491","x-ms-request-id":"7b674005-4b8e-4163-8916-02bca55b328a","x-ms-routing-request-id":"CANADACENTRAL:20191028T143915Z:605a32f2-b1f4-4d3b-b4dd-715b05904c62","Cache-Control":"no-cache","Date":"Mon, 28 Oct 2019 14:39:14 GMT","Server":"openresty/1.15.8.1"},"content":{"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"},"contentLength":459}
aM7qSd17daJy.js:1 content: {"properties":{"provisioningState":"Succeeded","configServerProperties":{"state":"Succeeded"},"trace":{"state":"NotAvailable","enabled":false,"appInsightInstrumentationKey":null},"version":2,"serviceId":"4cc14974de7946368f5f50119a6185a6"},"type":"Microsoft.AppPlatform/Spring","location":"westus2","tags":null,"id":"/subscriptions/9036e83e-2238-42a4-9b2a-ecd80d4cc38d/resourceGroups/rjones/providers/Microsoft.AppPlatform/Spring/jonestest","name":"jonestest"}
d54PHuFc6uBX.js:9 [AppPlatformExtension]  10:39:15 AM Extension/AppPlatformExtension/PartType/Resource$TracingBladeAdapter Resource$TracingBladeAdapter: _errorData: undefined
_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.Error"]
code: undefined
data: {
  <u>: {
    content: <function>i,
    onInputsSetPromiseState: <function>i,
    role: <number>,
    internal: <Object>,
    container: <e>,
    onInputsSetPromise: <i>,
    chrome: <Object>,
    getViewModelStart: <number>
  }
}
errorLevel: 2
extension: AppPlatformExtension
handled: undefined
innerErrors: ["message: Cannot read property 'length' of undefined\r\nstack: TypeError: Cannot read property 'length' of undefined\n    at d (https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3297)\n    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3234\n    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)\n    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5156\r\n"]
message: Part's onInputsSet promise failed.(id: AppPlatformExtension-fx-010-005)
name: Error
source: undefined
stack: Error: Part's onInputsSet promise failed.(id: AppPlatformExtension-fx-010-005)
    at new r (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:18:790)
    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:72:2971
    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)
    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5443
timestamp: 13712.330000009388
type: MsPortalFx.Errors.Error

r @ d54PHuFc6uBX.js:9
d54PHuFc6uBX.js:9 [AppPlatformExtension]  10:39:15 AM Base.ProxiedObservablesV2 241 Base.ProxiedObservablesV2: Po-241: 
{"message":"Cannot read property 'properties' of undefined","callstack":"TypeError: Cannot read property 'properties' of undefined\n    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/A5nB-lyFRmeE.js:1:6029\n    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10418)\n    at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9964)\n    at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9477)\n    at Function.peek (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10673)\n    at lo (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:9106)\n    at p (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:12169)\n    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5660\n    at li (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:2981)\n    at su (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5520)","pId":"AppPlatformExtension-fx-01","data":"AppPlatformExtension-fx-010-007:{\n  <t>: {\n    menuContent: <Object>,\n    subtitle: <function>i,\n    icon: <function>i,\n    statusBar: <function>i,\n    helpContentUri: <function>i,\n    title: <function>i,\n    commandBar: <t>,\n    contentSection: <t>,\n    emptyContentSection: <t>\n  }\n}"}
r @ d54PHuFc6uBX.js:9
d54PHuFc6uBX.js:9 [AppPlatformExtension]  10:39:22 AM MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Cannot read property 'length' of undefined
stack: TypeError: Cannot read property 'length' of undefined
    at d (https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3297)
    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/aM7qSd17daJy.js:1:3234
    at o (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:72)
    at https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:4:5156

r @ d54PHuFc6uBX.js:9
d54PHuFc6uBX.js:9 [AppPlatformExtension]  10:39:22 AM MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Cannot read property 'properties' of undefined
stack: TypeError: Cannot read property 'properties' of undefined
    at https://afd.hosting.portal.azure.net/appplatform/Content/Dynamic/A5nB-lyFRmeE.js:1:6029
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10418)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9964)
    at Function.evaluateImmediate (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:9477)
    at Function.peek (https://portal.azure.com/Content/Dynamic/HqqGcaigZQO_.js:52:10673)
    at lo (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:9106)
    at p (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:12169)
    at https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5660
    at li (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:2981)
    at su (https://portal.azure.com/Content/Dynamic/d54PHuFc6uBX.js:36:5520)

r @ d54PHuFc6uBX.js:9```

**Comment by xscript** [comment]
@1openwindow @Sneezry

**Comment by 1openwindow** [comment]
@sampeinado this issue was fixed. Please let us know if you still encounter this issue.
